// Generated by proxysim.c3pq.emit_batch_harness -- do not edit.
//
// One binary per batch. Each entry is an independently generated circuit whose symbols
// were given a private prefix by prefix_symbols(); entries sharing a group index are
// accumulated together with their weights, so the K Monte-Carlo trajectories of one
// noise realisation collapse to a single output before anything is written to disk.
#include <algorithm>
#include <complex>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>
#include <vector>
#include <mpi.h>
#include <omp.h>

#include "cal_n04_probe_k000_m.hpp"

typedef void (*apply_fn)(std::complex<double> *, std::complex<double> *, double *, int);

static const size_t DIM = 16ull;
static const int N_QUBITS = 4;
static const int N_ENTRIES = 1;
static const int N_GROUPS = 1;

static apply_fn const FN[] = {s00000_apply_l0_c0};
static const int ENTRY_GROUP[] = {0};
static const double ENTRY_WEIGHT[] = {1};
static const char *const ENTRY_NAME[] = {"cal_n04_probe_k000"};
static const char *const GROUP_NAME[] = {"cal_n04_probe"};
static const size_t TOPK = 1024ull;

int main(int argc, char **argv) {
    MPI_Init(&argc, &argv);
    int rank = 0, world = 1;
    MPI_Comm_rank(MPI_COMM_WORLD, &rank);
    MPI_Comm_size(MPI_COMM_WORLD, &world);
    // Every estimator below indexes the state vector globally. Under more than one rank
    // the layout after MPI_Alltoall is undocumented upstream, so refuse rather than
    // report a plausible wrong number.
    if (world != 1) {
        if (rank == 0)
            fprintf(stderr, "c3pq batch harness: single-rank only, launched with %d\n",
                    world);
        MPI_Abort(MPI_COMM_WORLD, 2);
    }

    int threads = (argc > 1) ? atoi(argv[1]) : 1;
    const char *outdir = (argc > 2) ? argv[2] : ".";
    omp_set_dynamic(0);
    omp_set_num_threads(threads > 0 ? threads : 1);

    std::vector<std::complex<double> > sv(DIM), tmp(DIM);
    std::vector<std::vector<double> > acc(
        N_GROUPS, std::vector<double>(DIM, 0.0));
    std::vector<double> norm(N_GROUPS, 0.0);

    for (int e = 0; e < N_ENTRIES; ++e) {
        std::fill(sv.begin(), sv.end(), std::complex<double>(0.0, 0.0));
        std::fill(tmp.begin(), tmp.end(), std::complex<double>(0.0, 0.0));
        sv[0] = std::complex<double>(1.0, 0.0);   // |0...0>, not the stock all-ones state

        double timing[3] = {0.0, 0.0, 0.0};
        double t0 = MPI_Wtime();
        FN[e](sv.data(), tmp.data(), timing, 2);   // result lands back in sv
        double t1 = MPI_Wtime();

        const int g = ENTRY_GROUP[e];
        const double w = ENTRY_WEIGHT[e];
        {
            double *a = acc[g].data();
            double s = 0.0;
#pragma omp parallel for reduction(+ : s) schedule(static)
            for (size_t i = 0; i < DIM; ++i) {
                double p = std::norm(sv[i]);
                a[i] += w * p;
                s += p;
            }
            norm[g] += w * s;
        }
        printf("entry\t%s\t%s\t%.6f\n", ENTRY_NAME[e], GROUP_NAME[g], t1 - t0);
        fflush(stdout);
    }

    {
        std::string path = std::string(outdir) + "/" + "b0000_n04_topk" + ".topk.tsv";
        FILE *f = fopen(path.c_str(), "w");
        if (!f) { fprintf(stderr, "cannot write %s\n", path.c_str()); MPI_Abort(MPI_COMM_WORLD, 3); }
        fprintf(f, "group\tindex\tprob\tnorm\tretained\n");
        std::vector<size_t> order(DIM);
        for (int g = 0; g < N_GROUPS; ++g) {
            for (size_t i = 0; i < DIM; ++i) order[i] = i;
            const double *a = acc[g].data();
            size_t k = (TOPK < DIM) ? TOPK : DIM;
            std::partial_sort(order.begin(), order.begin() + k, order.end(),
                              [a](size_t x, size_t y) { return a[x] > a[y]; });
            double retained = 0.0;
            for (size_t i = 0; i < k; ++i) retained += a[order[i]];
            for (size_t i = 0; i < k; ++i)
                fprintf(f, "%s\t%zu\t%.17g\t%.17g\t%.17g\n", GROUP_NAME[g],
                        order[i], a[order[i]], norm[g], retained);
        }
        fclose(f);
    }
    MPI_Finalize();
    return 0;
}
