// Generated by proxysim.c3pq.emit_batch_harness -- do not edit.
//
// One binary per batch. Each entry is an independently generated circuit whose symbols
// were given a private prefix by prefix_symbols(); entries sharing a group index are
// accumulated together with their weights, so the K Monte-Carlo trajectories of one
// noise realisation collapse to a single output before anything is written to disk.
#include <algorithm>
#include <complex>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>
#include <vector>
#include <mpi.h>
#include <omp.h>

#include "cb_n04_random_cA_cbd024_r000_ideal_k000_m.hpp"
#include "cb_n04_random_cA_cbd024_r000_noisy_k000_m.hpp"
#include "cb_n04_random_cB_cbd024_r000_ideal_k000_m.hpp"
#include "cb_n04_random_cB_cbd024_r000_noisy_k000_m.hpp"

typedef void (*apply_fn)(std::complex<double> *, std::complex<double> *, double *, int);

static const size_t DIM = 16ull;
static const int N_QUBITS = 4;
static const int N_ENTRIES = 4;
static const int N_GROUPS = 4;

static apply_fn const FN[] = {s00000_apply_l0_c0, s00001_apply_l0_c0, s00002_apply_l0_c0, s00003_apply_l0_c0};
static const int ENTRY_GROUP[] = {0, 1, 2, 3};
static const double ENTRY_WEIGHT[] = {1, 1, 1, 1};
static const char *const ENTRY_NAME[] = {"cb_n04_random_cA_cbd024_r000_ideal_k000", "cb_n04_random_cA_cbd024_r000_noisy_k000", "cb_n04_random_cB_cbd024_r000_ideal_k000", "cb_n04_random_cB_cbd024_r000_noisy_k000"};
static const char *const GROUP_NAME[] = {"cb_n04_random_cA_cbd024_r000_ideal", "cb_n04_random_cA_cbd024_r000_noisy", "cb_n04_random_cB_cbd024_r000_ideal", "cb_n04_random_cB_cbd024_r000_noisy"};
static const unsigned long long MASK_LSB[] = {15, 15, 6, 6};
static const unsigned long long MASK_MSB[] = {15, 15, 6, 6};
static const int SIGN[] = {-1, -1, -1, -1};

int main(int argc, char **argv) {
    MPI_Init(&argc, &argv);
    int rank = 0, world = 1;
    MPI_Comm_rank(MPI_COMM_WORLD, &rank);
    MPI_Comm_size(MPI_COMM_WORLD, &world);
    // Every estimator below indexes the state vector globally. Under more than one rank
    // the layout after MPI_Alltoall is undocumented upstream, so refuse rather than
    // report a plausible wrong number.
    if (world != 1) {
        if (rank == 0)
            fprintf(stderr, "c3pq batch harness: single-rank only, launched with %d\n",
                    world);
        MPI_Abort(MPI_COMM_WORLD, 2);
    }

    int threads = (argc > 1) ? atoi(argv[1]) : 1;
    const char *outdir = (argc > 2) ? argv[2] : ".";
    omp_set_dynamic(0);
    omp_set_num_threads(threads > 0 ? threads : 1);

    std::vector<std::complex<double> > sv(DIM), tmp(DIM);
    std::vector<double> par_lsb(N_GROUPS, 0.0), par_msb(N_GROUPS, 0.0);
    std::vector<double> norm(N_GROUPS, 0.0);

    for (int e = 0; e < N_ENTRIES; ++e) {
        std::fill(sv.begin(), sv.end(), std::complex<double>(0.0, 0.0));
        std::fill(tmp.begin(), tmp.end(), std::complex<double>(0.0, 0.0));
        sv[0] = std::complex<double>(1.0, 0.0);   // |0...0>, not the stock all-ones state

        double timing[3] = {0.0, 0.0, 0.0};
        double t0 = MPI_Wtime();
        FN[e](sv.data(), tmp.data(), timing, 2);   // result lands back in sv
        double t1 = MPI_Wtime();

        const int g = ENTRY_GROUP[e];
        const double w = ENTRY_WEIGHT[e];
        {
            const unsigned long long m0 = MASK_LSB[g], m1 = MASK_MSB[g];
            double s0 = 0.0, s1 = 0.0, s = 0.0;
#pragma omp parallel for reduction(+ : s0, s1, s) schedule(static)
            for (size_t i = 0; i < DIM; ++i) {
                double p = std::norm(sv[i]);
                s += p;
                s0 += (__builtin_parityll(i & m0) ? -p : p);
                s1 += (__builtin_parityll(i & m1) ? -p : p);
            }
            par_lsb[g] += w * s0;
            par_msb[g] += w * s1;
            norm[g] += w * s;
        }
        printf("entry\t%s\t%s\t%.6f\n", ENTRY_NAME[e], GROUP_NAME[g], t1 - t0);
        fflush(stdout);
    }

    {
        std::string path = std::string(outdir) + "/" + "b0002_n04_parity" + ".parity.tsv";
        FILE *f = fopen(path.c_str(), "w");
        if (!f) { fprintf(stderr, "cannot write %s\n", path.c_str()); MPI_Abort(MPI_COMM_WORLD, 3); }
        fprintf(f, "group\tsign\tparity_lsb\tparity_msb\tnorm\n");
        for (int g = 0; g < N_GROUPS; ++g)
            fprintf(f, "%s\t%d\t%.17g\t%.17g\t%.17g\n", GROUP_NAME[g], SIGN[g],
                    SIGN[g] * par_lsb[g], SIGN[g] * par_msb[g], norm[g]);
        fclose(f);
    }
    MPI_Finalize();
    return 0;
}
