"""Unified simulation interface.

Supported simulators
--------------------
    statevector | sv | qiskit
    tensornetwork | tn | mps | quimb
    stabilizer | stim | clifford
    pauliprop
    auto

Supported outputs
-----------------
    distribution
    samples
    survival
    expectation

Noisy statevector and tensor-network calculations use Monte-Carlo trajectories
generated by ``sample_trajectory``. Noise is therefore handled consistently for
Clifford and non-Clifford circuits.

The stabilizer backend remains available for noiseless Clifford simulation.
Noisy Stim simulation is intentionally not used by this module.
"""

from __future__ import annotations

import dataclasses
import random
from typing import Optional

import numpy as np

from . import metrics  # noqa: F401
from .backends import (
    StabilizerBackend,
    StatevectorBackend,
    TensorNetworkBackend,
)
from .noise import sample_trajectory


_SV_ALIASES = {"statevector", "sv", "qiskit"}
_TN_ALIASES = {"tensornetwork", "tn", "mps", "quimb"}
_STAB_ALIASES = {"stabilizer", "stim", "clifford"}


# ---------------------------------------------------------------------------
# Backend selection
# ---------------------------------------------------------------------------
def auto_simulator(circuit) -> str:
    """Choose a backend automatically.

    The statevector backend is preferred for Clifford circuits because noisy
    simulation is trajectory based and no longer depends on Stim.
    """
    if circuit.n_qubits <= 24:
        return "statevector"

    return "tensornetwork"


def make_backend(
    simulator: str,
    max_bond: Optional[int] = None,
    gpu: bool = False,
):
    """Construct a backend from a simulator name."""
    simulator = simulator.lower()

    if simulator in _SV_ALIASES:
        return StatevectorBackend()

    if simulator in _TN_ALIASES:
        return TensorNetworkBackend(
            max_bond=max_bond,
            gpu=gpu,
        )

    if simulator in _STAB_ALIASES:
        return StabilizerBackend()

    raise ValueError(f"unknown simulator '{simulator}'")


# ---------------------------------------------------------------------------
# Noise-model compatibility helpers
# ---------------------------------------------------------------------------
def _without_readout(noise):
    """Return a copy of the noise model with assignment error disabled.

    This supports both the original ``p_readout`` API and the generalized
    asymmetric ``p_readout_01``/``p_readout_10`` API.
    """
    if noise is None:
        return None

    field_names = {
        field.name
        for field in dataclasses.fields(noise)
    }

    updates = {}

    if "p_readout" in field_names:
        updates["p_readout"] = 0.0

    if "p_readout_01" in field_names:
        updates["p_readout_01"] = 0.0

    if "p_readout_10" in field_names:
        updates["p_readout_10"] = 0.0

    return dataclasses.replace(noise, **updates)


def _readout_probabilities(noise):
    """Return asymmetric assignment-error probabilities."""
    if noise is None or not getattr(noise, "enabled", True):
        return 0.0, 0.0

    if hasattr(noise, "p_readout_01"):
        p01 = float(noise.p_readout_01)
    else:
        p01 = float(getattr(noise, "p_readout", 0.0))

    if hasattr(noise, "p_readout_10"):
        p10 = float(noise.p_readout_10)
    else:
        p10 = float(getattr(noise, "p_readout", 0.0))

    return p01, p10


# ---------------------------------------------------------------------------
# Distribution conversion
# ---------------------------------------------------------------------------
def _as_dense_distribution(distribution, n_qubits: int) -> np.ndarray:
    """Convert a backend distribution to a dense probability vector."""
    dimension = 2**n_qubits

    if isinstance(distribution, dict):
        dense = np.zeros(dimension, dtype=float)

        for key, probability in distribution.items():
            if isinstance(key, str):
                index = int(key.replace(" ", ""), 2)
            else:
                index = int(key)

            dense[index] += float(probability)

        return dense

    dense = np.asarray(distribution, dtype=float).reshape(-1)

    if dense.size != dimension:
        raise ValueError(
            "Distribution has length "
            f"{dense.size}, expected {dimension} for {n_qubits} qubits."
        )

    total = float(np.sum(dense))

    if total > 0.0:
        dense = dense / total

    return dense


def _sample_counts(
    distribution: np.ndarray,
    n_qubits: int,
    shots: int,
    seed: int,
):
    """Sample bitstring counts from a dense probability distribution."""
    shots = max(int(shots), 1)

    probability = np.asarray(distribution, dtype=float)
    probability = np.clip(probability, 0.0, None)

    total = float(np.sum(probability))
    if total <= 0.0:
        raise ValueError("Cannot sample from a zero-mass distribution.")

    probability /= total

    rng = np.random.default_rng(seed)
    outcomes = rng.choice(
        probability.size,
        size=shots,
        p=probability,
    )

    counts = {}
    for outcome in outcomes:
        bitstring = format(int(outcome), f"0{n_qubits}b")
        counts[bitstring] = counts.get(bitstring, 0) + 1

    return counts


def _apply_readout_to_distribution(
    distribution: np.ndarray,
    n_qubits: int,
    noise,
) -> np.ndarray:
    """Apply independent asymmetric classical readout error exactly.

    ``p_readout_01`` is interpreted as P(measure 1 | true 0).
    ``p_readout_10`` is interpreted as P(measure 0 | true 1).
    """
    p01, p10 = _readout_probabilities(noise)

    if p01 <= 0.0 and p10 <= 0.0:
        return np.asarray(distribution, dtype=float)

    current = np.asarray(distribution, dtype=float).reshape(
        (2,) * n_qubits
    )

    assignment = np.array(
        [
            [1.0 - p01, p10],
            [p01, 1.0 - p10],
        ],
        dtype=float,
    )

    for axis in range(n_qubits):
        current = np.tensordot(
            assignment,
            current,
            axes=([1], [axis]),
        )

        current = np.moveaxis(
            current,
            0,
            axis,
        )

    result = current.reshape(-1)
    result = np.clip(result, 0.0, None)

    total = float(np.sum(result))
    if total > 0.0:
        result /= total

    return result


# ---------------------------------------------------------------------------
# Trajectory workers
# ---------------------------------------------------------------------------
def _sv_distribution_worker(args):
    circuit, noise, seed = args

    backend = StatevectorBackend()
    rng = random.Random(seed)

    noisy_circuit = sample_trajectory(
        circuit,
        noise,
        rng,
    )

    distribution = backend.exact_distribution(noisy_circuit)

    return _as_dense_distribution(
        distribution,
        circuit.n_qubits,
    )


def _tn_distribution_worker(args):
    circuit, noise, max_bond, gpu, seed = args

    backend = TensorNetworkBackend(
        max_bond=max_bond,
        gpu=gpu,
    )
    rng = random.Random(seed)

    noisy_circuit = sample_trajectory(
        circuit,
        noise,
        rng,
    )

    distribution = backend.exact_distribution(noisy_circuit)

    return _as_dense_distribution(
        distribution,
        circuit.n_qubits,
    )


def _sv_prob0_worker(args):
    circuit, noise, seed = args

    backend = StatevectorBackend()
    rng = random.Random(seed)

    noisy_circuit = sample_trajectory(
        circuit,
        noise,
        rng,
    )

    return float(backend.prob0(noisy_circuit))


def _tn_prob0_worker(args):
    circuit, noise, max_bond, gpu, seed = args

    backend = TensorNetworkBackend(
        max_bond=max_bond,
        gpu=gpu,
    )
    rng = random.Random(seed)

    noisy_circuit = sample_trajectory(
        circuit,
        noise,
        rng,
    )

    return float(backend.prob0(noisy_circuit))


def _run_workers(
    worker,
    arguments,
    parallel: bool,
    n_workers,
):
    if parallel:
        from .parallel import pmap

        return pmap(
            worker,
            arguments,
            n_workers=n_workers,
            executor="process",
        )

    return [worker(argument) for argument in arguments]


# ---------------------------------------------------------------------------
# Noisy full distribution
# ---------------------------------------------------------------------------
def noisy_distribution(
    circuit,
    noise,
    simulator="statevector",
    n_traj=200,
    seed=0,
    max_bond=None,
    gpu=False,
    parallel=False,
    n_workers=None,
    include_readout=True,
):
    """Average noisy output probabilities over Monte-Carlo trajectories."""
    simulator = simulator.lower()

    # Readout is a classical post-processing channel. It should not be inserted
    # as a quantum gate by the trajectory sampler.
    trajectory_noise = _without_readout(noise)

    n_traj = max(int(n_traj), 1)

    if simulator in _SV_ALIASES:
        worker = _sv_distribution_worker
        arguments = [
            (
                circuit,
                trajectory_noise,
                seed + trajectory_index + 1,
            )
            for trajectory_index in range(n_traj)
        ]

    elif simulator in _TN_ALIASES:
        worker = _tn_distribution_worker
        arguments = [
            (
                circuit,
                trajectory_noise,
                max_bond,
                gpu,
                seed + trajectory_index + 1,
            )
            for trajectory_index in range(n_traj)
        ]

    elif simulator in _STAB_ALIASES:
        raise NotImplementedError(
            "Noisy stabilizer simulation is disabled. "
            "Use simulator='statevector' or simulator='tensornetwork'."
        )

    else:
        raise ValueError(
            f"noisy_distribution: unsupported simulator '{simulator}'"
        )

    trajectory_distributions = _run_workers(
        worker,
        arguments,
        parallel=parallel,
        n_workers=n_workers,
    )

    average = np.mean(
        np.asarray(trajectory_distributions, dtype=float),
        axis=0,
    )

    average = np.clip(average, 0.0, None)

    total = float(np.sum(average))
    if total > 0.0:
        average /= total

    if include_readout:
        average = _apply_readout_to_distribution(
            average,
            circuit.n_qubits,
            noise,
        )

    return average


# ---------------------------------------------------------------------------
# Noisy survival probability
# ---------------------------------------------------------------------------
def noisy_survival(
    circuit,
    noise,
    simulator="auto",
    n_traj=2000,
    seed=0,
    max_bond=None,
    gpu=False,
    parallel=False,
    n_workers=None,
):
    """Return mean P(0...0), excluding readout assignment error."""
    simulator = (
        auto_simulator(circuit)
        if simulator == "auto"
        else simulator.lower()
    )

    trajectory_noise = _without_readout(noise)
    n_traj = max(int(n_traj), 1)

    if simulator in _SV_ALIASES:
        worker = _sv_prob0_worker
        arguments = [
            (
                circuit,
                trajectory_noise,
                seed + trajectory_index + 1,
            )
            for trajectory_index in range(n_traj)
        ]

    elif simulator in _TN_ALIASES:
        worker = _tn_prob0_worker
        arguments = [
            (
                circuit,
                trajectory_noise,
                max_bond,
                gpu,
                seed + trajectory_index + 1,
            )
            for trajectory_index in range(n_traj)
        ]

    elif simulator in _STAB_ALIASES:
        raise NotImplementedError(
            "Noisy stabilizer survival is disabled. "
            "Use simulator='statevector' or simulator='tensornetwork'."
        )

    else:
        raise ValueError(
            f"noisy_survival: unsupported simulator '{simulator}'"
        )

    values = _run_workers(
        worker,
        arguments,
        parallel=parallel,
        n_workers=n_workers,
    )

    return float(np.mean(values))


# ---------------------------------------------------------------------------
# Compatibility helper
# ---------------------------------------------------------------------------
def noisy_tvd_vs_support(
    circuit,
    noise,
    ideal_support,
    shots,
    seed,
    simulator="statevector",
):
    """Estimate TVD against a uniform ideal support.

    This replaces the old Stim-specific coset implementation.
    """
    distribution = noisy_distribution(
        circuit,
        noise,
        simulator=simulator,
        n_traj=max(int(shots), 1),
        seed=seed,
    )

    support = list(ideal_support)
    ideal = np.zeros(2**circuit.n_qubits, dtype=float)

    if support:
        ideal[np.asarray(support, dtype=int)] = 1.0 / len(support)

    return 0.5 * float(np.sum(np.abs(distribution - ideal)))


# ---------------------------------------------------------------------------
# Unified dispatcher
# ---------------------------------------------------------------------------
def simulate(
    circuit,
    simulator="auto",
    output="distribution",
    noise=None,
    shots=0,
    seed=1234,
    max_bond=None,
    gpu=False,
    observable=None,
    n_traj=2000,
    parallel=False,
    n_workers=None,
):
    """Dispatch simulation according to simulator and requested output."""
    simulator = (
        auto_simulator(circuit)
        if simulator == "auto"
        else simulator.lower()
    )

    output = output.lower()

    # ------------------------------------------------------------------
    # Pauli expectation propagation
    # ------------------------------------------------------------------
    if output == "expectation" or simulator == "pauliprop":
        from .pauliprop_validator import PauliPropagator

        if observable is None:
            observable = "Z" + "_" * (
                circuit.n_qubits - 1
            )

        return PauliPropagator(
            max_weight=max_bond
        ).expectation(
            circuit,
            observable,
        )

    backend = make_backend(
        simulator,
        max_bond=max_bond,
        gpu=gpu,
    )

    # ------------------------------------------------------------------
    # Full output distribution
    # ------------------------------------------------------------------
    if output == "distribution":
        if noise is None or not getattr(noise, "enabled", True):
            exact = backend.exact_distribution(circuit)

            return _as_dense_distribution(
                exact,
                circuit.n_qubits,
            )

        # Preserve the existing calling convention:
        #
        # simulate(..., output="distribution", shots=TVD_SHOTS)
        #
        # Here shots controls the number of trajectories unless n_traj is
        # explicitly changed from its default.
        trajectory_count = (
            int(shots)
            if int(shots) > 0
            else int(n_traj)
        )

        return noisy_distribution(
            circuit,
            noise,
            simulator=simulator,
            n_traj=trajectory_count,
            seed=seed,
            max_bond=max_bond,
            gpu=gpu,
            parallel=parallel,
            n_workers=n_workers,
            include_readout=True,
        )

    # ------------------------------------------------------------------
    # Measurement samples
    # ------------------------------------------------------------------
    if output == "samples":
        shots = max(int(shots), 1)

        if noise is None or not getattr(noise, "enabled", True):
            result = backend.run(
                circuit,
                shots=shots,
                seed=seed,
            )

            return result.counts

        distribution = noisy_distribution(
            circuit,
            noise,
            simulator=simulator,
            n_traj=max(int(n_traj), 1),
            seed=seed,
            max_bond=max_bond,
            gpu=gpu,
            parallel=parallel,
            n_workers=n_workers,
            include_readout=True,
        )

        return _sample_counts(
            distribution,
            circuit.n_qubits,
            shots,
            seed,
        )

    # ------------------------------------------------------------------
    # Survival probability P(0...0)
    # ------------------------------------------------------------------
    if output == "survival":
        if noise is None or not getattr(noise, "enabled", True):
            return float(backend.prob0(circuit))

        return noisy_survival(
            circuit,
            noise,
            simulator=simulator,
            n_traj=n_traj,
            seed=seed,
            max_bond=max_bond,
            gpu=gpu,
            parallel=parallel,
            n_workers=n_workers,
        )

    raise ValueError(f"unknown output '{output}'")


# """One intuitive entry point: ``simulate(circuit, simulator=..., output=...)``.

# Everything the package can do is reachable from here with a readable if-else over
# two axes:

#   simulator :  'statevector' | 'tensornetwork' | 'stabilizer' | 'pauliprop' | 'auto'
#   output    :  'distribution' | 'samples' | 'survival' | 'expectation'

# plus flags: ``noise`` (a NoiseModel), ``gpu`` (tensor-network on cupy),
# ``max_bond`` (MPS truncation), and ``parallel``/``n_workers`` (fan trajectories or
# shots across a node). 'auto' picks the stabilizer backend for Clifford circuits and
# the tensor-network backend otherwise.

# Noisy outputs: a Clifford circuit is sampled natively by stim (exact, scalable);
# a non-Clifford circuit is handled by Monte-Carlo trajectories on the statevector /
# MPS backend, which parallelise across a node.
# """

# from __future__ import annotations

# import dataclasses
# import random
# from typing import Optional

# import numpy as np

# from . import metrics  # noqa: F401  (kept for convenience re-export)
# from .backends import StabilizerBackend, StatevectorBackend, TensorNetworkBackend
# from .noise import sample_trajectory, to_stim_noisy

# _SV_ALIASES = {"statevector", "sv", "qiskit"}
# _TN_ALIASES = {"tensornetwork", "tn", "mps", "quimb"}
# _STAB_ALIASES = {"stabilizer", "stim", "clifford"}


# def auto_simulator(circuit) -> str:
#     return "stabilizer" if circuit.is_clifford else "tensornetwork"


# def noisy_tvd_vs_support(circuit, noise, ideal_support, shots, seed):
#     """TVD of the stim-sampled noisy Clifford circuit vs a known uniform ideal
#     support (the 'coset trick': works at 20 qubits because we only need the sampled
#     counts on the ideal outcomes plus the leftover mass). ``ideal_support`` is an
#     iterable of integer codes (bit j of the code is qubit j, q0 = MSB)."""
#     arr = to_stim_noisy(circuit, noise).compile_sampler(seed=seed).sample(shots)
#     n = circuit.n_qubits
#     weights = (1 << np.arange(n - 1, -1, -1)).astype(np.int64)   # q0 = MSB
#     codes = arr.astype(np.int64) @ weights
#     vals, cnts = np.unique(codes, return_counts=True)
#     counts = dict(zip(vals.tolist(), cnts.tolist()))
#     return metrics.tvd_to_ideal_support(counts, shots, list(ideal_support))


# def make_backend(simulator: str, max_bond: Optional[int] = None, gpu: bool = False):
#     """Return a backend instance for a simulator name (with GPU / bond options)."""
#     s = simulator.lower()
#     if s in _SV_ALIASES:
#         return StatevectorBackend()
#     if s in _TN_ALIASES:
#         return TensorNetworkBackend(max_bond=max_bond, gpu=gpu)
#     if s in _STAB_ALIASES:
#         return StabilizerBackend()
#     raise ValueError(f"unknown simulator '{simulator}'")


# # ---------------------------------------------------------------------------
# # Top-level trajectory workers (must be importable so process workers can pickle).
# # ---------------------------------------------------------------------------
# def _sv_prob0_worker(args):
#     circuit, noise, seed = args
#     return StatevectorBackend().prob0(sample_trajectory(circuit, noise, random.Random(seed)))


# def _tn_prob0_worker(args):
#     circuit, noise, max_bond, gpu, seed = args
#     tn = TensorNetworkBackend(max_bond=max_bond, gpu=gpu)
#     return tn.prob0(sample_trajectory(circuit, noise, random.Random(seed)))


# # ---------------------------------------------------------------------------
# # Noisy survival probability P(0...0) -- the mirror-circuit error metric.
# # ---------------------------------------------------------------------------
# def noisy_survival(circuit, noise, simulator="auto", n_traj=2000, seed=0,
#                    max_bond=None, gpu=False, parallel=False, n_workers=None):
#     """Mean P(0...0) of the noisy circuit. Stim-native for Clifford circuits, else
#     Monte-Carlo trajectories on statevector / MPS (readout handled by the caller)."""
#     sim = auto_simulator(circuit) if simulator == "auto" else simulator.lower()
#     noise = dataclasses.replace(noise, p_readout=0.0)  # readout folded in via ro_fid

#     if sim in _STAB_ALIASES and circuit.is_clifford:
#         arr = to_stim_noisy(circuit, noise).compile_sampler(seed=seed).sample(n_traj)
#         return float(np.mean(np.all(arr == 0, axis=1)))

#     if sim in _SV_ALIASES:
#         worker, make_args = _sv_prob0_worker, lambda s: (circuit, noise, s)
#     elif sim in _TN_ALIASES:
#         worker, make_args = _tn_prob0_worker, lambda s: (circuit, noise, max_bond, gpu, s)
#     else:
#         raise ValueError(f"noisy_survival: simulator '{simulator}' can't do this circuit")

#     arglist = [make_args(seed + i + 1) for i in range(n_traj)]
#     if parallel:
#         from .parallel import pmap
#         vals = pmap(worker, arglist, n_workers=n_workers, executor="process")
#     else:
#         vals = [worker(a) for a in arglist]
#     return float(np.mean(vals))


# # ---------------------------------------------------------------------------
# # The unified dispatcher.
# # ---------------------------------------------------------------------------
# def simulate(circuit, simulator="auto", output="distribution", noise=None,
#              shots=0, seed=1234, max_bond=None, gpu=False, observable=None,
#              n_traj=2000, parallel=False, n_workers=None):
#     """Dispatch by (simulator, output). See module docstring for the axes."""
#     sim = auto_simulator(circuit) if simulator == "auto" else simulator.lower()

#     # -- expectation values go through Pauli propagation, a separate modality --
#     if output == "expectation" or sim == "pauliprop":
#         from .pauliprop_validator import PauliPropagator
#         if observable is None:
#             observable = "Z" + "_" * (circuit.n_qubits - 1)
#         return PauliPropagator(max_weight=max_bond).expectation(circuit, observable)

#     backend = make_backend(sim, max_bond=max_bond, gpu=gpu)

#     if output == "distribution":
#         if noise is None:
#             return backend.exact_distribution(circuit)
#         # noisy distribution: stim samples it natively for Clifford circuits
#         if circuit.is_clifford:
#             arr = to_stim_noisy(circuit, noise).compile_sampler(seed=seed).sample(max(shots, 1))
#             counts = {}
#             for row in arr:
#                 k = "".join("1" if b else "0" for b in row)
#                 counts[k] = counts.get(k, 0) + 1
#             tot = sum(counts.values()) or 1
#             return {k: v / tot for k, v in counts.items()}
#         raise NotImplementedError("noisy full distribution for non-Clifford: use "
#                                   "output='survival' (or aggregate trajectories yourself)")

#     if output == "samples":
#         return backend.run(circuit, shots=shots, seed=seed).counts

#     if output == "survival":
#         if noise is None:
#             return backend.prob0(circuit)
#         return noisy_survival(circuit, noise, simulator=sim, n_traj=n_traj, seed=seed,
#                               max_bond=max_bond, gpu=gpu, parallel=parallel,
#                               n_workers=n_workers)

#     raise ValueError(f"unknown output '{output}'")
