"""Explicit-RC QCAP bound and raw TVD scatter versus CX-cycle depth for MQT QPE.

Circuit:
    qpe11.qasm

The imported circuit contains 12 qubits:
    * 11 measured counting qubits
    * 1 unmeasured ancilla

Cycle convention
----------------
A cycle is one ASAP-parallel layer of CX gates. Distinct CX-layer patterns are
benchmarked with cycle benchmarking. Under the homogeneous synthetic noise model,
patterns containing the same number of simultaneous CX gates share one CB estimate.

For each complete-circuit repetition count d:

    logical target = U^d
    CX-cycle depth = d * number_of_CX_layers_in_U

Each raw TVD point is generated by:

    1. Constructing U^d.
    2. Generating independently randomized-compiled versions of U^d.
    3. Marking inserted Pauli dressing gates as virtual frame changes.
    4. Simulating noisy trajectories under the ORIGINAL NoiseModel.
    5. Excluding virtual frame gates from p1 and idle-noise accounting.
    6. Applying readout noise analytically.
    7. Marginalizing onto the measured counting qubits.
    8. Averaging distributions across trajectories and RC realizations.
    9. Computing TVD only after all averaging.

Because the QPE entanglers are CX gates, they are Clifford and support the full
Pauli randomized-compiling construction used by proxysim.rc.pauli_twirl.

Run:
    python examples/run_qpe_explicit_rc_bound_tvd.py
"""

from __future__ import annotations

import inspect
import os
import random
import warnings
from collections import Counter
from typing import Any, Collection, Tuple

warnings.filterwarnings("ignore")

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
import numpy as np
from qiskit.quantum_info import Statevector

import _bootstrap  # noqa: F401
from proxysim import NoiseModel, save_results
from proxysim.backends import StatevectorBackend
from proxysim.benchmarking import (
    cycle_benchmark,
    qcap_bound,
    readout_fidelity,
)
from proxysim.circuit import circuit_from_qasm
from proxysim.mqtbank import repeat
from proxysim.noise import (
    apply_readout_to_distribution,
    sample_trajectory,
)
from proxysim.parallel import pmap
from proxysim.rc import pauli_twirl


# =============================================================================
# Configuration
# =============================================================================

QASM = os.path.join(
    os.path.dirname(__file__),
    "qpe11.qasm",
)

# Complete repetitions of the imported QASM circuit.
REPETITIONS = [1, 2, 4, 8, 16]

# Sequence lengths used inside cycle benchmarking.
CB_DEPTHS = [1, 2, 4, 8]

# Fixed physical noise throughout the depth sweep.
NOISE = NoiseModel(
    enabled=True,
    p1=1e-5,
    p2=2.5e-4,
    p_readout=2.5e-4,
    p_idle=5e-5,
    p_z1=0.0,
    p_zz=0.0,
    theta_1q=0.0,
    theta_zz=0.0,
)

# Number of independent raw TVD estimates plotted at every depth.
N_TVD_POINTS = 30

# Number of independently dressed circuits averaged into one TVD point.
N_RC_REALIZATIONS = 24

# Number of stochastic noise trajectories per dressed circuit.
#
# Total statevector trajectories per TVD point:
#
#     N_RC_REALIZATIONS * N_TRAJ_PER_RC
N_TRAJ_PER_RC = 12

# Cycle-benchmark statistics.
CB_SHOTS = 800
CB_DECAYS = 20

SEED = 42

OUT = (
    _bootstrap.RESULTS_DIR
    + "/qpe_explicit_rc_bound_tvd.png"
)

OUT_DATA = (
    _bootstrap.RESULTS_DIR
    + "/qpe_explicit_rc_bound_tvd_data.npz"
)

_SV = StatevectorBackend()


# =============================================================================
# RC return-value compatibility
# =============================================================================

def _looks_like_circuit(obj: Any) -> bool:
    """Return whether obj resembles a proxysim Circuit."""
    return (
        obj is not None
        and hasattr(obj, "gates")
        and hasattr(obj, "n_qubits")
    )


def _normalize_virtual_indices(
    virtual: Any,
) -> Tuple[int, ...]:
    """Normalize virtual-gate indices returned by pauli_twirl."""
    if virtual is None:
        return ()

    if isinstance(virtual, dict):
        return tuple(
            sorted(int(index) for index in virtual)
        )

    if isinstance(virtual, np.ndarray):
        return tuple(
            int(index)
            for index in virtual.tolist()
        )

    if (
        isinstance(virtual, Collection)
        and not isinstance(virtual, (str, bytes))
    ):
        return tuple(
            int(index)
            for index in virtual
        )

    raise TypeError(
        "Could not interpret pauli_twirl's virtual-gate report. "
        f"Received {type(virtual).__name__}."
    )


def _extract_dressed_and_virtual(
    result: Any,
) -> Tuple[Any, Tuple[int, ...]]:
    """Extract dressed circuit and virtual indices from pauli_twirl output."""
    if result is None:
        raise RuntimeError(
            "pauli_twirl returned None."
        )

    if isinstance(result, dict):
        circuit = None

        for key in (
            "circuit",
            "compiled_circuit",
            "dressed_circuit",
            "twirled_circuit",
        ):
            if key in result:
                circuit = result[key]
                break

        if circuit is None:
            raise TypeError(
                "pauli_twirl returned a dictionary without a recognized "
                f"circuit key. Keys: {list(result)}"
            )

        virtual = ()

        for key in (
            "virtual",
            "virtual_indices",
            "virtual_gates",
            "frame_indices",
        ):
            if key in result:
                virtual = _normalize_virtual_indices(
                    result[key]
                )
                break

        return circuit, virtual

    if isinstance(result, tuple):
        if not result:
            raise TypeError(
                "pauli_twirl returned an empty tuple."
            )

        if len(result) == 1:
            return result[0], ()

        first, second = result[0], result[1]

        if _looks_like_circuit(first):
            return (
                first,
                _normalize_virtual_indices(second),
            )

        if _looks_like_circuit(second):
            return (
                second,
                _normalize_virtual_indices(first),
            )

        raise TypeError(
            "Could not identify a circuit in pauli_twirl's tuple return. "
            f"Types: {[type(item).__name__ for item in result]}"
        )

    if hasattr(result, "circuit"):
        circuit = result.circuit
        virtual = ()

        for attr in (
            "virtual",
            "virtual_indices",
            "virtual_gates",
            "frame_indices",
        ):
            if hasattr(result, attr):
                virtual = _normalize_virtual_indices(
                    getattr(result, attr)
                )
                break

        return circuit, virtual

    if _looks_like_circuit(result):
        return result, ()

    raise TypeError(
        "Could not extract a dressed circuit from pauli_twirl output. "
        f"Received {type(result).__name__}."
    )


def explicitly_randomized_compile(
    circ,
    seed: int,
):
    """Return (dressed circuit, virtual dressing-gate indices).

    mark_virtual=True is essential. The inserted Pauli frame operations must
    remain part of the circuit unitary but must not receive physical p1 noise,
    create extra physical layers, or alter spectator-idle accounting.
    """
    try:
        parameters = inspect.signature(
            pauli_twirl
        ).parameters
    except (TypeError, ValueError):
        parameters = {}

    attempts = []

    if (
        "seed" in parameters
        and "mark_virtual" in parameters
    ):
        attempts.append(
            lambda: pauli_twirl(
                circ,
                seed=seed,
                mark_virtual=True,
            )
        )

    if (
        "rng" in parameters
        and "mark_virtual" in parameters
    ):
        attempts.append(
            lambda: pauli_twirl(
                circ,
                rng=random.Random(seed),
                mark_virtual=True,
            )
        )

    if (
        "random_state" in parameters
        and "mark_virtual" in parameters
    ):
        attempts.append(
            lambda: pauli_twirl(
                circ,
                random_state=random.Random(seed),
                mark_virtual=True,
            )
        )

    attempts.extend(
        [
            lambda: pauli_twirl(
                circ,
                seed=seed,
                mark_virtual=True,
            ),
            lambda: pauli_twirl(
                circ,
                rng=random.Random(seed),
                mark_virtual=True,
            ),
            lambda: pauli_twirl(
                circ,
                random.Random(seed),
                mark_virtual=True,
            ),
            lambda: pauli_twirl(
                circ,
                seed,
                mark_virtual=True,
            ),
        ]
    )

    errors = []

    for attempt in attempts:
        try:
            result = attempt()

            dressed, virtual = (
                _extract_dressed_and_virtual(result)
            )

            if not _looks_like_circuit(dressed):
                raise TypeError(
                    "Extracted object is not a proxysim-like Circuit."
                )

            return dressed, virtual

        except TypeError as exc:
            errors.append(str(exc))

    raise TypeError(
        "Could not call proxysim.rc.pauli_twirl with "
        "mark_virtual=True.\nObserved errors:\n  - "
        + "\n  - ".join(errors)
    )


# =============================================================================
# Circuit and cycle utilities
# =============================================================================

def cx_layer_patterns(circ):
    """Return Counter{CX-layer pattern: occurrences} for one circuit repetition.

    Each pattern is a frozenset of the CX pairs appearing in one ASAP layer.
    """
    patterns = Counter()

    for layer in circ.layers():
        pairs = frozenset(
            tuple(gate.qubits)
            for gate in layer
            if (
                len(gate.qubits) == 2
                and gate.name.lower() == "cx"
            )
        )

        if pairs:
            patterns[pairs] += 1

    return patterns


def exact_probability_vector(circ) -> np.ndarray:
    """Return the ideal full-register computational-basis distribution."""
    return np.asarray(
        Statevector(
            _SV._build(circ)
        ).probabilities(),
        dtype=float,
    )


def marginalize_distribution(
    probability: np.ndarray,
    n_qubits: int,
    measured_qubits,
) -> np.ndarray:
    """Marginalize a full distribution onto measured_qubits.

    The flat vector follows Qiskit's little-endian statevector indexing.
    Reshaping to [2] * n maps array axis k to qubit n - 1 - k.
    """
    measured_set = set(measured_qubits)

    drop_axes = tuple(
        n_qubits - 1 - qubit
        for qubit in range(n_qubits)
        if qubit not in measured_set
    )

    tensor = np.asarray(
        probability,
        dtype=float,
    ).reshape([2] * n_qubits)

    if drop_axes:
        tensor = tensor.sum(
            axis=drop_axes
        )

    return tensor.reshape(-1)


def measured_readout_noise(
    full_probability: np.ndarray,
    noise: NoiseModel,
    n_qubits: int,
    measured_qubits,
) -> np.ndarray:
    """Apply readout flips only to qubits measured by the QASM circuit.

    apply_readout_to_distribution applies flips to every qubit in its input,
    so first marginalize to the measured subsystem and then apply an equivalent
    NoiseModel on the reduced distribution.
    """
    measured_probability = marginalize_distribution(
        full_probability,
        n_qubits,
        measured_qubits,
    )

    return apply_readout_to_distribution(
        measured_probability,
        noise,
        len(measured_qubits),
    )


def ideal_statevector(circ) -> np.ndarray:
    """Return the ideal pure state of a proxysim circuit."""
    return np.asarray(
        Statevector(
            _SV._build(circ)
        ).data,
        dtype=complex,
    )


def state_fidelity(
    psi: np.ndarray,
    phi: np.ndarray,
) -> float:
    """Pure-state fidelity, insensitive to global phase."""
    return float(
        abs(np.vdot(psi, phi)) ** 2
    )


# =============================================================================
# CB construction
# =============================================================================

def cb_cycle_worker(args):
    """Benchmark one CX-layer proxy cycle."""
    pairs, n_qubits, seed, n_decays = args

    return cycle_benchmark(
        list(pairs),
        n_qubits,
        CB_DEPTHS,
        NOISE,
        twoq="CX",
        n_decays=n_decays,
        shots=CB_SHOTS,
        seed=seed,
    )


def benchmark_cycle_patterns(
    circ,
    patterns,
    n_measured: int,
):
    """Benchmark each distinct CX-layer class needed by the QCAP bound.

    Under the homogeneous model, e_F is cached by the number of simultaneous
    CX gates in the layer. Pattern occurrence counts are retained separately.
    """
    readout_fid, readout_std = readout_fidelity(
        n_measured,
        NOISE,
        seed=3,
    )

    representative_by_size = {}

    for pattern in patterns:
        size = len(pattern)

        if size not in representative_by_size:
            representative_by_size[size] = pattern

    jobs = [
        (
            representative_by_size[size],
            circ.n_qubits,
            100 + size,
            CB_DECAYS,
        )
        for size in sorted(representative_by_size)
    ]

    results = pmap(
        cb_cycle_worker,
        jobs,
        n_workers=max(1, (os.cpu_count() or 2) - 2),
    )

    ef_by_ncx = {
        size: (
            float(result["e_F"]),
            float(result["e_F_std"]),
        )
        for size, result in zip(
            sorted(representative_by_size),
            results,
        )
    }

    counts_one_rep = {}
    cycle_efs = {}

    for index, (pattern, count) in enumerate(
        patterns.items()
    ):
        key = f"pattern_{index}"
        counts_one_rep[key] = int(count)
        cycle_efs[key] = ef_by_ncx[len(pattern)]

    return (
        counts_one_rep,
        cycle_efs,
        readout_fid,
        readout_std,
        ef_by_ncx,
    )


# =============================================================================
# Explicit-RC TVD worker
# =============================================================================

def rc_averaged_measured_tvd(args):
    """Produce one explicit-RC TVD estimate on the measured QPE register.

    Averaging order:

        trajectory mean within each RC realization
        then mean over RC realizations
        then TVD against the ideal measured distribution
    """
    (
        target,
        noise,
        ideal_measured_probability,
        measured_qubits,
        n_rc_realizations,
        n_traj_per_rc,
        seed,
    ) = args

    n_qubits = target.n_qubits

    rc_average = np.zeros_like(
        ideal_measured_probability,
        dtype=float,
    )

    for rc_index in range(n_rc_realizations):
        rc_seed = (
            seed
            + 1_000_003 * rc_index
        )

        dressed, virtual_indices = (
            explicitly_randomized_compile(
                target,
                seed=rc_seed,
            )
        )

        trajectory_rng = random.Random(
            rc_seed + 1
        )

        full_probability = np.zeros(
            2 ** n_qubits,
            dtype=float,
        )

        for _ in range(n_traj_per_rc):
            noisy_dressed = sample_trajectory(
                dressed,
                noise,
                trajectory_rng,
                virtual=virtual_indices,
            )

            state = np.asarray(
                Statevector(
                    _SV._build(noisy_dressed)
                ).data,
                dtype=complex,
            )

            full_probability += (
                np.abs(state) ** 2
            )

        full_probability /= n_traj_per_rc

        measured_probability = measured_readout_noise(
            full_probability,
            noise,
            n_qubits,
            measured_qubits,
        )

        rc_average += measured_probability

    rc_average /= n_rc_realizations

    return 0.5 * float(
        np.abs(
            rc_average
            - ideal_measured_probability
        ).sum()
    )


def scatter_summary(values) -> str:
    """Return mean and range of one raw-TVD scatter column."""
    values = np.asarray(
        values,
        dtype=float,
    )

    return (
        f"{values.mean():.5f} "
        f"[{values.min():.5f}, {values.max():.5f}]"
    )


# =============================================================================
# Validation
# =============================================================================

def validate_one_rc_realization(base_circ):
    """Check RC logical equivalence and virtual-gate reporting."""
    dressed, virtual_indices = (
        explicitly_randomized_compile(
            base_circ,
            seed=SEED,
        )
    )

    original_state = ideal_statevector(
        base_circ
    )

    dressed_state = ideal_statevector(
        dressed
    )

    fidelity = state_fidelity(
        original_state,
        dressed_state,
    )

    original_twoq = sum(
        len(gate.qubits) == 2
        for gate in base_circ.gates
    )

    dressed_twoq = sum(
        len(gate.qubits) == 2
        for gate in dressed.gates
    )

    print(
        "explicit-RC smoke test:\n"
        f"    original gates:       {len(base_circ.gates)}\n"
        f"    dressed gates:        {len(dressed.gates)}\n"
        f"    original 2q gates:    {original_twoq}\n"
        f"    dressed 2q gates:     {dressed_twoq}\n"
        f"    virtual RC gates:     {len(virtual_indices)}\n"
        f"    ideal-state fidelity: {fidelity:.12f}\n"
    )

    if not virtual_indices:
        warnings.warn(
            "pauli_twirl reported no virtual-gate indices. If Pauli dressing "
            "gates were inserted, they may be incorrectly charged physical "
            "one-qubit and idle noise.",
            RuntimeWarning,
        )

    if not np.isclose(
        fidelity,
        1.0,
        atol=1e-9,
        rtol=1e-9,
    ):
        raise RuntimeError(
            "The RC-dressed circuit is not logically equivalent to the "
            "original QPE circuit. A returned frame correction may not have "
            "been applied, or the pauli_twirl return contract differs from "
            "the forms handled by this script."
        )


# =============================================================================
# Main
# =============================================================================

def main():
    with open(
        QASM,
        encoding="utf-8",
    ) as qasm_file:
        base_circ, measured = circuit_from_qasm(
            qasm_file.read()
        )

    measured = tuple(
        sorted(int(qubit) for qubit in measured)
    )

    n_qubits = base_circ.n_qubits

    ancillas = [
        qubit
        for qubit in range(n_qubits)
        if qubit not in measured
    ]

    patterns = cx_layer_patterns(
        base_circ
    )

    cycles_per_rep = sum(
        patterns.values()
    )

    if cycles_per_rep == 0:
        raise ValueError(
            "No ASAP CX-cycle layers were found in qpe11.qasm."
        )

    n_cx = sum(
        1
        for gate in base_circ.gates
        if (
            len(gate.qubits) == 2
            and gate.name.lower() == "cx"
        )
    )

    print(base_circ.summary())

    print(
        f"register size: {n_qubits} qubits\n"
        f"measured counting qubits: {len(measured)} {list(measured)}\n"
        f"unmeasured ancilla qubits: {ancillas}\n"
        f"CX gates per repetition: {n_cx}\n"
        f"ASAP CX cycles per repetition: {cycles_per_rep}\n"
        f"distinct CX-layer patterns: {len(patterns)}\n"
        f"simultaneous-CX layer sizes: "
        f"{sorted(set(len(pattern) for pattern in patterns))}"
    )

    print(
        "cycle convention: each ASAP-parallel CX layer, together with its "
        "nearby one-qubit operations, is one CB/RC cycle"
    )

    print(
        "TVD protocol: explicitly Pauli-dress the CX gates, simulate the "
        "dressed circuit under the original noise model, average the output "
        "distributions, and marginalize to the measured register"
    )

    print(
        f"fixed noise:\n"
        f"    p1={NOISE.p1:.3e}\n"
        f"    p2={NOISE.p2:.3e}\n"
        f"    p_readout={NOISE.p_readout:.3e}\n"
        f"    p_idle={NOISE.p_idle:.3e}\n"
        f"    p_z1={NOISE.p_z1:.3e}\n"
        f"    p_zz={NOISE.p_zz:.3e}\n"
        f"    theta_1q={NOISE.theta_1q:.3e}\n"
        f"    theta_zz={NOISE.theta_zz:.3e}\n"
    )

    n_workers = max(
        1,
        (os.cpu_count() or 2) - 2,
    )

    validate_one_rc_realization(
        base_circ
    )

    (
        counts_one_rep,
        cycle_efs,
        readout_fid,
        readout_std,
        ef_by_ncx,
    ) = benchmark_cycle_patterns(
        base_circ,
        patterns,
        len(measured),
    )

    print(
        "cycle-benchmark results:"
    )

    for n_simultaneous_cx in sorted(
        ef_by_ncx
    ):
        ef, ef_std = ef_by_ncx[
            n_simultaneous_cx
        ]

        print(
            f"    {n_simultaneous_cx} simultaneous CX: "
            f"e_F={ef:.6f} +/- {ef_std:.6f}"
        )

    print(
        f"    measured-register readout fidelity: "
        f"{readout_fid:.6f} +/- {readout_std:.6f}\n"
    )

    cycle_depths = []
    qcap_bounds = []
    qcap_stds = []
    all_tvd_points = []
    ideal_supports = []

    print(
        f"{'reps':>6}"
        f"{'CX cycles':>12}"
        f"{'CX gates':>11}"
        f"{'support':>12}"
        f"{'QCAP':>12}"
        f"{'RC TVD mean [min,max]':>32}"
    )

    for repetition in REPETITIONS:
        target = repeat(
            base_circ,
            repetition,
        )

        cycle_depth = (
            repetition
            * cycles_per_rep
        )

        expected_cx = (
            repetition
            * n_cx
        )

        actual_cx = sum(
            1
            for gate in target.gates
            if (
                len(gate.qubits) == 2
                and gate.name.lower() == "cx"
            )
        )

        if actual_cx != expected_cx:
            raise RuntimeError(
                "Unexpected CX count after circuit repetition: "
                f"expected {expected_cx}, found {actual_cx}."
            )

        cycle_depths.append(
            cycle_depth
        )

        ideal_full = exact_probability_vector(
            target
        )

        ideal_measured = marginalize_distribution(
            ideal_full,
            n_qubits,
            measured,
        )

        support = int(
            np.count_nonzero(
                ideal_measured > 1e-12
            )
        )

        ideal_supports.append(
            support
        )

        repetition_counts = {
            cycle_name: count * repetition
            for cycle_name, count in counts_one_rep.items()
        }

        bound = qcap_bound(
            repetition_counts,
            cycle_efs,
            readout_fid,
            readout_std,
        )

        qcap_bounds.append(
            float(bound["error"])
        )

        qcap_stds.append(
            float(bound["std"])
        )

        jobs = [
            (
                target,
                NOISE,
                ideal_measured,
                measured,
                N_RC_REALIZATIONS,
                N_TRAJ_PER_RC,
                (
                    SEED
                    + 100_000_000 * repetition
                    + 100_000 * point_index
                ),
            )
            for point_index in range(
                N_TVD_POINTS
            )
        ]

        tvd_values = pmap(
            rc_averaged_measured_tvd,
            jobs,
            n_workers=n_workers,
        )

        tvd_values = np.asarray(
            tvd_values,
            dtype=float,
        )

        all_tvd_points.append(
            tvd_values
        )

        print(
            f"{repetition:>6}"
            f"{cycle_depth:>12}"
            f"{actual_cx:>11}"
            f"{support:>12}"
            f"{bound['error']:>12.5f}"
            f"{scatter_summary(tvd_values):>32}",
            flush=True,
        )

    cycle_depths = np.asarray(
        cycle_depths,
        dtype=int,
    )

    qcap_bounds = np.asarray(
        qcap_bounds,
        dtype=float,
    )

    qcap_stds = np.asarray(
        qcap_stds,
        dtype=float,
    )

    all_tvd_points = np.asarray(
        all_tvd_points,
        dtype=float,
    )

    save_results(
        OUT_DATA,
        repetitions=np.asarray(
            REPETITIONS,
            dtype=int,
        ),
        cycle_depths=cycle_depths,
        qcap_bound=qcap_bounds,
        qcap_bound_std=qcap_stds,
        tvd_points=all_tvd_points,
        ideal_support=np.asarray(
            ideal_supports,
            dtype=int,
        ),
        cycles_per_rep=cycles_per_rep,
        cx_gates_per_rep=n_cx,
        measured_qubits=np.asarray(
            measured,
            dtype=int,
        ),
        readout_fidelity=readout_fid,
        readout_fidelity_std=readout_std,
        n_tvd_points=N_TVD_POINTS,
        n_rc_realizations=N_RC_REALIZATIONS,
        n_traj_per_rc=N_TRAJ_PER_RC,
        total_trajectories_per_tvd=(
            N_RC_REALIZATIONS
            * N_TRAJ_PER_RC
        ),
    )

    # -------------------------------------------------------------------------
    # Plot only the requested deliverables
    # -------------------------------------------------------------------------

    fig, ax = plt.subplots(
        figsize=(9.2, 5.8)
    )

    for index, cycle_depth in enumerate(
        cycle_depths
    ):
        ax.plot(
            np.full(
                N_TVD_POINTS,
                cycle_depth,
            ),
            all_tvd_points[index],
            "o",
            color="#0072B2",
            ms=5.5,
            alpha=0.60,
            label=(
                "explicit-RC measured-register TVD"
                if index == 0
                else None
            ),
        )

    ax.plot(
        cycle_depths,
        qcap_bounds,
        "-",
        color="#D55E00",
        lw=2.6,
        label="QCAP bound from CX-cycle CB",
    )

    lower = np.clip(
        qcap_bounds
        - 2.96 * qcap_stds,
        0.0,
        1.0,
    )

    upper = np.clip(
        qcap_bounds
        + 2.96 * qcap_stds,
        0.0,
        1.0,
    )

    ax.fill_between(
        cycle_depths,
        lower,
        upper,
        color="#D55E00",
        alpha=0.18,
        linewidth=0,
        label="QCAP fit uncertainty",
    )

    ax.axhline(
        1.0,
        color="0.5",
        lw=0.8,
        ls=":",
    )

    ax.set_xlabel(
        "number of applied ASAP CX cycles"
    )

    ax.set_ylabel(
        "total variation distance / bound"
    )

    ax.set_title(
        "QPE-11: explicit-RC TVD versus CX-cycle QCAP bound\n"
        "12-qubit circuit; TVD evaluated on the 11 measured qubits"
    )

    ax.set_ylim(
        -0.03,
        1.05,
    )

    ax.grid(
        True,
        alpha=0.15,
    )

    ax.legend(
        frameon=False,
    )

    fig.tight_layout()

    fig.savefig(
        OUT,
        dpi=160,
        bbox_inches="tight",
    )

    print(
        f"\nWrote {OUT}"
    )

    print(
        f"Wrote {OUT_DATA}"
    )


if __name__ == "__main__":
    main()